name: Cypress Parallel Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main, master ]

jobs:
  install:
    runs-on: mac-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

  2x-chrome:
    needs: install
    runs-on: mac-latest
    strategy:
      fail-fast: false
      matrix:
        machines: [1, 2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for server and run Chrome tests
        run: npm run test:ci:chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STANDARD_USERNAME: ${{ secrets.STANDARD_USERNAME }}
          STANDARD_PASSWORD: ${{ secrets.STANDARD_PASSWORD }}
          VISUAL_USERNAME: ${{ secrets.VISUAL_USERNAME }}
          VISUAL_PASSWORD: ${{ secrets.VISUAL_PASSWORD }}
          START_SERVER_AND_TEST_INSECURE: 1

  2x-firefox:
    needs: install
    runs-on: mac-latest
    strategy:
      fail-fast: false
      matrix:
        machines: [1, 2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for server and run Firefox tests
        run: npm run test:ci:firefox
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STANDARD_USERNAME: ${{ secrets.STANDARD_USERNAME }}
          STANDARD_PASSWORD: ${{ secrets.STANDARD_PASSWORD }}
          VISUAL_USERNAME: ${{ secrets.VISUAL_USERNAME }}
          VISUAL_PASSWORD: ${{ secrets.VISUAL_PASSWORD }}
          START_SERVER_AND_TEST_INSECURE: 1

  4x-electron:
    needs: install
    runs-on: mac-latest
    strategy:
      fail-fast: false
      matrix:
        machines: [1, 2, 3, 4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for server and run Electron tests
        run: npm run test:ci:electron
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STANDARD_USERNAME: ${{ secrets.STANDARD_USERNAME }}
          STANDARD_PASSWORD: ${{ secrets.STANDARD_PASSWORD }}
          VISUAL_USERNAME: ${{ secrets.VISUAL_USERNAME }}
          VISUAL_PASSWORD: ${{ secrets.VISUAL_PASSWORD }}
          START_SERVER_AND_TEST_INSECURE: 1 