name: Cypress Parallel Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main, master ]

jobs:
  install:
    runs-on: mac-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

  2x-chrome:
    needs: install
    runs-on: mac-latest
    strategy:
      fail-fast: false
      matrix:
        machines: [1, 2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Chrome Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
          parallel: true
          group: '2x-chrome'
          spec: |
            cypress/e2e/features/simultaneous_checkout.feature
            cypress/e2e/features/transaction.feature
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STANDARD_USERNAME: ${{ secrets.STANDARD_USERNAME }}
          STANDARD_PASSWORD: ${{ secrets.STANDARD_PASSWORD }}
          VISUAL_USERNAME: ${{ secrets.VISUAL_USERNAME }}
          VISUAL_PASSWORD: ${{ secrets.VISUAL_PASSWORD }}

  2x-firefox:
    needs: install
    runs-on: mac-latest
    strategy:
      fail-fast: false
      matrix:
        machines: [1, 2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Firefox Tests
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
          record: true
          parallel: true
          group: '2x-firefox'
          spec: |
            cypress/e2e/features/simultaneous_checkout.feature
            cypress/e2e/features/transaction.feature
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STANDARD_USERNAME: ${{ secrets.STANDARD_USERNAME }}
          STANDARD_PASSWORD: ${{ secrets.STANDARD_PASSWORD }}
          VISUAL_USERNAME: ${{ secrets.VISUAL_USERNAME }}
          VISUAL_PASSWORD: ${{ secrets.VISUAL_PASSWORD }}

  4x-electron:
    needs: install
    runs-on: mac-latest
    strategy:
      fail-fast: false
      matrix:
        machines: [1, 2, 3, 4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Electron Tests
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          group: '4x-electron'
          spec: |
            cypress/e2e/features/simultaneous_checkout.feature
            cypress/e2e/features/transaction.feature
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STANDARD_USERNAME: ${{ secrets.STANDARD_USERNAME }}
          STANDARD_PASSWORD: ${{ secrets.STANDARD_PASSWORD }}
          VISUAL_USERNAME: ${{ secrets.VISUAL_USERNAME }}
          VISUAL_PASSWORD: ${{ secrets.VISUAL_PASSWORD }} 